### ISSUE TITLE
Top-level downloads.digitalcorpora.org is a 404

### ISSUE THREAD

**Issue by ajnelson-nist** [digitalcorpora/app#9]
This URL provides a 404 page:
https://downloads.digitalcorpora.org/

What is the behavior we'd expect of the path `/`?

**Comment by ajnelson-nist** [comment]
Stylistically, I don't know what this would best be.

**Comment by simsong** [comment]
It's an excellent question. One option is just listing the bucket. Another option is showing a static HTML page or the README.html. Because it requires special casing, I haven't implement it yet. But I'm open to suggestions!

**Comment by simsong** [comment]
No longer; I added a placeholders.
![image](https://user-images.githubusercontent.com/1594284/107870314-089a1500-6e65-11eb-97e5-33293a07e2b3.png)
